<?php

namespace RTFMIS\Covoiturage\TripBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OneWayTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneWayTripRepository extends EntityRepository
{
}
