parameters:
#    rtfmis_covoiturage_trip.example.class: RTFMIS\Covoiturage\TripBundle\Example

services:
#    rtfmis_covoiturage_trip.example:
#        class: %rtfmis_covoiturage_trip.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
